In [19]:
import numpy as np 

def link_matrix(matrix): #adjacentcy matrix for directed graph cpmverted into link matrix
    n = matrix.shape[0]
    L = np.zeros((n,n)) #square matrix the same size as the adj matrix
    for j in range(n):
        links = np.where(matrix[:, j])[0] # finds the index of page connects to j
        n_link = len(links)
        if n_link > 0:
            L[links,j] = 1/n_link # 1/j  where the page j links page i
    return L

def transition_matrix(link_matrix,dampening, e_jumpvec):
    n = link_matrix.shape[0] 
    T = np.zeros((n,n))
    
    for j in range(n):
        if np.sum(link_matrix[:,j]) == 0: # if no links then colum = e
            T[:, j] = e_jumpvec 
        else:
            T[:,j] = (1-dampening) * link_matrix[:,j] + dampening*e_jumpvec
            # Tij = (1-d) * Lij + d * ei
    return T

def power_iteration(T, tolerance, iterations):
    n = T.shape[0]
    R = np.ones(n) / n
    
    for i in range(iterations):
        R_next = np.matmul(T,R)
        # T is already normalized
        if np.linalg.norm(R_next - R, 1) < tolerance:
        # check how much values changes as an absolute value
            print(f"Converge in {i+1} iterations")
            break
        R = R_next
    return R

            

matrix1 = np.array([
    [0, 0, 1, 0],
    [0, 0, 1, 0],
    [1, 1, 0, 1],
    [0, 1, 0, 0],
], dtype=float)

example_matrix = np.array([
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [1, 1, 0, 0],
], dtype=float)

def print_output(matrix):
    n = matrix.shape[0]
    L = link_matrix(matrix)
    print(f"Link Matrix: \n{L}")
    e = np.ones(n) / n # probability that a jump between link lands on another value in the matrix
    d = 0.15 # probability a user will visit another link
    T = transition_matrix(L, d, e)
    print(f"Transition Matrix: \n{T}")
    tolerance = 1e-6
    iteration = 100
    R = power_iteration(T, tolerance, iteration)

    for i, val in enumerate(R):
        print(f"Page {i}: {val:.4f}")

print("Start of Matrix 1 Demo")        
print_output(matrix1)
print("End of Matrix 1")
print("Start of Matrix 2 Demo")
print_output(example_matrix)
print("End of Matrix 2")
    




    

Start of Matrix 1 Demo
Link Matrix: 
[[0.  0.  0.5 0. ]
 [0.  0.  0.5 0. ]
 [1.  0.5 0.  1. ]
 [0.  0.5 0.  0. ]]
Transition Matrix: 
[[0.0375 0.0375 0.4625 0.0375]
 [0.0375 0.0375 0.4625 0.0375]
 [0.8875 0.4625 0.0375 0.8875]
 [0.0375 0.4625 0.0375 0.0375]]
Converge in 21 iterations
Page 0: 0.2199
Page 1: 0.2199
Page 2: 0.4292
Page 3: 0.1310
End of Matrix 1
Start of Matrix 2 Demo
Link Matrix: 
[[0.5 0.5 1.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.5 0.  0. ]]
Transition Matrix: 
[[0.4625 0.4625 0.8875 0.8875]
 [0.0375 0.0375 0.0375 0.0375]
 [0.0375 0.0375 0.0375 0.0375]
 [0.4625 0.4625 0.0375 0.0375]]
Converge in 17 iterations
Page 0: 0.6116
Page 1: 0.0375
Page 2: 0.0375
Page 3: 0.3134
End of Matrix 2
